### PR TITLE
Redesign?

### PR DESCRIPTION
**Pull request by Speculative**
Consider the colors and other aesthetics unfinalized. Looking for critique on layout/interaction. No, I haven't yet made it mobile compatible.

http://speculative.s-ul.eu/oFHymht9

### CODE REVIEW

**Comment by Speculative** [comment]
Also TODO: infinite scroll

**Comment by nolanlum** [comment]
nice, UX increased by 100%

style-wise I'm personally more a fan of light color schemes, but that's like personal preference. why not make the topbar full-width (with a fixed-width content area)? it seems more common; see: github et al. also what I think would be a good idea would be to move the search inputbox in between the brand/home link (also changing the home link to "qdb" or whatever name it or a logo instead of "Home") so we can do a right-aligned login/logout thing. (because we will eventually add users?)

I'm also not a huge fan of the border around the topbar but that's like a minor aesthetic nit.

also I think the add quote modal should have a nontransparent background too to reduce the visual noise.

**Comment by Speculative** [comment]
So we look like this now: http://speculative.s-ul.eu/4RAZFDNa

**Comment by Speculative** [comment]
TODO: Infinite scroll, paste modal preview. But maybe those are separate PRs. This is mergeable as-is.

**Pull request merged**
