### PR TITLE
support CRLF in log parsers

### PR DESCRIPTION
**Pull request by Adjective-Object**

### CODE REVIEW

**Comment by Speculative** [comment]
Tested this out, looks like it's not CRLF that's causing the issue for me. I think it's a bunch of unrecognized cases? I get the following when copying out of Discord (I have no clue why our discords generate such different copy-pastes):

```
Jay Tau - Today at 10:10 PM
!aku kemono friends
```
```
PJ - Yesterday at 12:21 AM
This DLC pack adDS “Revealing Outfit” costume for 2B, “Young Man’s Outfit” costume for 9S and “Destroyer Outfit” costume for A2. AfteR completing new sub-quests in this DLC, you CAn enJOy playing the game while WearINg these costumes from NieR Replicant. Sub-quests take the form of tHRee different battle challenges at three diffERenT colosseums. Special music video: NieR:Automata meets amazarashi “Deserving of Life,” from colLAboratiON with rock band amazarashi, is alSo iNCLudeD as part of the scenario. We hoPe you hAVe fuN with this conTenT.
```
```
Jay Tau - Last Tuesday at 11:15 PM
!aku ohhh
!aku ohhh
```
```
Jay Tau - 04/26/2017
!aku reload
!aku liberal media
!aku sax
```

For reference, this is what you have commented for paste format for Discord
```
[9:06 PM] Wheatless: wow gj gabe
[9:06 PM] PJ: [tiff snaps into the sunset
```

And out of Slack from people who have statuses set (note the newline and the reversed order of name/timestamp
```
Jeff Tao 
[4:25 PM] 
I would probably not be much good at weeb karaoke

gabe
[4:29 PM] 
yes you would

[4:29] 
Don't lie to yourself

[4:29] 
Don't lie to your _soul_.

Jeff Tao 
[4:29 PM] 
I don't know Japanese

[4:29] 
like at all

gabe
[4:29 PM] 
Don't :clap: lie :clap: to :clap: your :clap: _soul_ (edited)
```

As opposed to without a status:
```
Max [7:59 PM] 
did ellipticles today

[7:59] 
holy lord jesus my thighs

[7:59] 
how do people do so much ellipticling
```

**Comment by Speculative** [comment]
FWIW I fixed the slack newline case by replacing the regex with this:
```
const slackHeaderRegex = /^(.+?[^\s])(\s+)\[\d{1,2}:\d{2} (A|P)M\](\s+)?/;
```

Note the change in the second capturing group from `( |$(\r\n|\n)?)` to `(\s+)`

**Comment by Speculative** [comment]
I wrote like half a regex for the weird discord format but it doesn't work (don't know how to make it match the body of the message without running over the start of the next author/timestamp line). Posting it here in case it's helpful tomorrow
```
(.+) - (\w+) at (\d{1,2}:\d{2} [AP]M)\n(.|\n)+
```

**Comment by Adjective-Object** [comment]
There is an existing dependent branch (parse-discord-multiline) to handle fixes for the discord parser that you implemented here (though I'm pretty sure the replacement you did here is too accepting?)

I'd advise either rolling back the changes here or abandoning this pull and just working on that one.

**Comment by Adjective-Object** [comment]
updated PR @ #6

**Pull request closed without merging**
