### PR TITLE
Frontend mock

### PR DESCRIPTION
**Pull request by Adjective-Object**
basic placeholder of some frontend components
image

### CODE REVIEW

**Comment by nolanlum** [comment]
how does this concept extend to "chat log" style quotes where there's not a clear source for attribution? the original qdb was a clone of http://bash.org/ and I think a lot of the contributed content will be of a similar format.

**Comment by Adjective-Object** [comment]
For the time being, reverted to plain monospace text.

image

A future feature worth discussing could be parsing chatlogs from slack/discord/irc into a structured format in order to capture back&fourths, emoji, profile pictures, etc.

**Comment by nolanlum** [comment]
seems legit. I'd also display the quote number somewhere in the UI, since that's the user-friendly identifier for deeplinking, etc.

things to think about: submit flow, topbar?, increased layout width?

**Comment by nolanlum** [comment]
looks good to merge

**Pull request merged**
